package: genai_detection
version: 0.1.0
name: GenAI Detection
description: A Python package for detecting AI-generated images and videos.
seed: 42
upload_dataset:
  dataset_name: "stable-diffusion-laion"
  data_path: "../data/01_raw/*tar.gz"

download_dataset:
  artifact_id: "stable-diffusion-laion:v2"

test_download:
  artifact_id: "test:v0"

train_config:
  epochs: 10
  batch_size: 32
  learning_rate: 0.001
  model_name: "resnet18"
  momentum: 0.9

wandb_config:
  entity: genai-detectio
  project: genai-detection