FROM python:3.10-bookworm

RUN apt-get -y update && apt-get -y install git

RUN pip install --upgrade pip

RUN useradd -m -u 1000 user

USER user

ENV HOME=/home/user \
	PATH=/home/user/.local/bin:$PATH

WORKDIR $HOME/app

RUN pip install --no-cache-dir --upgrade pip

RUN pip install --no-cache-dir --upgrade --user pip poetry

COPY --chown=user . $HOME/app/

RUN poetry install --with api --with gradio

ENTRYPOINT [ "poetry", "run", "bash", "scripts/app.sh" ]